### PR TITLE
Return objects from client

### LINKED ISSUE #16: Client functions return Axios Responses
The responses returned from the Client are the Axios responses rather than just the data from the response. I'm happy to PR the changes but wanted to be sure there wasn't a reason for this before doing the work. 

I am really enjoying Drone. Keep up the great work

### PR DESCRIPTION
**Pull request by rtirserio**
Resolves #16 

Adds a middleware that will only return the data from the requests. For errors, the entire error is returned but this could be changed to only include fields like the message and stack.

I also fixed the unit tests as they were never getting into the then function to verify the shape of the data being returned.

### CODE REVIEW

**Comment by tboerger** [comment]
Are you able to add a fallback for the existing installations? You can see the references at https://github.com/drone/drone-node/network/dependents?package_id=UGFja2FnZS0xNjM0NDQzNA%3D%3D

**Comment by tboerger** [comment]
Not sure if it's worth it as only the top one got recent commits.

**Comment by rtirserio** [comment]
If the version is updated to a major version release, it would indicate major potentially breaking changes. Speaking of versions, are you able to get this new version into the npm registry at some point?

**Comment by tboerger** [comment]
Yeah that's true... I will be able to tag a release, hopefully I won't forget until I'm back at a computer 😂

**Comment by tboerger** [comment]
I have tagged it as v2.1.0 now... It's currently building and publishing at https://cloud.drone.io/drone/drone-node/11

**Comment by jshields-squarespace** [comment]
@tboerger It looks like this breaking change was released as a minor version update (`2.0.0 -> 2.1.0`). Was that intentional?

**Pull request merged**
